server.port=8082
spring.application.name=user-service

# ---------- Database (user_db - owned exclusively by User Service) ----------
spring.datasource.url=jdbc:mysql://localhost:3306/job_user_db1?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Aniket@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ---------- File upload (resumes) ----------
app.upload.dir=./uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

logging.level.com.joborbit.user=DEBUG
